//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Window
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHoaDon { get; set; }
        public Nullable<int> MaDatPhong { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string NhanVienThanhToan { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> TienDichVu { get; set; }
        public Nullable<int> TongTien { get; set; }
    
        public virtual DatPhong DatPhong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
